"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS: list[str] = config('DJANGO_ALLOWED_HOSTS', cast=Csv()) # type: ignore


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.qras',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apps.config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'apps.qras.modules.authentication.context_processors.user_permissions',
                # 'apps.qras.modules.authentication.context_processors.clock_offset',
            ],
        },
    },
]

WSGI_APPLICATION = 'apps.config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':   config('DB_ENGINE',     default='django.db.backends.postgresql'),
        'NAME':     config('DB_NAME',       default='db_qras'),
        'USER':     config('DB_USER',       default='postgres'),
        'PASSWORD': config('DB_PASSWORD',   default='postgres'),
        'HOST':     config('DB_HOST',       default='localhost'),
        'PORT':     config('DB_PORT',       default='5432'),
    },
    'server': {
        'ENGINE':   config('SERVER_DB_ENGINE',      default='django.db.backends.postgresql'),
        'NAME':     config('SERVER_DB_NAME',        default='db_qras'),
        'USER':     config('SERVER_DB_USER',        default='postgres'),
        'PASSWORD': config('SERVER_DB_PASSWORD',    default='postgres'),
        'HOST':     config('SERVER_DB_HOST',        default='localhost'),
        'PORT':     config('SERVER_DB_PORT',        default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default page/gateway (Login, etc.) redirect URL after login
# https://docs.djangoproject.com/en/6.1/topics/auth/default/#the-login-required-decorator

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'scanner'


# Media files (Uploaded files)
# https://docs.djangoproject.com/en/6.1/topics/files/
MEDIA_URL = 'apps/qras/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND':  config('EMAIL_BACKEND',         default='django.core.mail.backends.smtp.EmailBackend'),
        'HOST':     config('EMAIL_HOST',            default='smtp.gmail.com'),
        'PORT':     config('EMAIL_PORT',            default=587, cast=int),
        'USERNAME': config('EMAIL_HOST_USER',       default='mbpi.itsupport@gmail.com'),
        'PASSWORD': config('EMAIL_HOST_PASSWORD',   default='secret'),
        'USE_TLS':  config('EMAIL_USE_TLS',         default=True, cast=bool),
    },
}

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL',   default='mbpi.itsupport@gmail.com')


# Seconds -- reset link valid for 1 hour
PASSWORD_RESET_TIMEOUT  = 3600  

"""

Extra Configs for QRAS
https://docs.djangoproject.com/en/6.1/topics/settings/#custom-settings
    
"""

# Temp cache files for storage
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / '.cache',
    }
}

# Initialized role name
ADMIN_ROLE_NAME = config('ADMIN_ROLE_NAME', default='Administrator')

# Loggers
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "suppress_browser_polyfill": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: "browser-polyfill.js.map" not in record.getMessage(),
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["suppress_browser_polyfill"],
        }
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        }
    },
}